/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce.compra;

import bancoDados.BD;
import ecommerce.cliente.TelaSecundariaCliente;
import ecommerce.usuario.session;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan Farina
 */
public class Carrinho extends javax.swing.JFrame {

    /**
     * Creates new form Carrinho
     */
    BD bd = new BD();
    public Carrinho() {
        initComponents();
        bd.conecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_item = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quant = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        Remover = new javax.swing.JButton();
        pesquisa = new javax.swing.JButton();
        AreaCliente = new javax.swing.JButton();
        Comprar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Comprarmais = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Connection con = null;
        Statement st = null;
        ResultSet rs = null; String s;

        //connect your app to mysql database

        try{
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://ec2-34-195-115-225.compute-1.amazonaws.com:5432/d7gbh9tbts0r7j","zuidrqukwykbwd","8f82c803a029137f140288c3d133e854bdf76d61b948c7ad1365552d7f058d69");
            st = con.createStatement();
            s = "select id_produto,cpf_cliente,quant,preco_total from carrinho where cpf_cliente = '"+session.getInstance().getCPF()+"' AND aberto = 's'";
            rs = st.executeQuery(s);
            ResultSetMetaData rsmt = rs.getMetaData();
            int c = rsmt.getColumnCount();
            Vector column = new Vector(c);

            for(int i = 1; i <= c; i++) {
                column.add(rsmt.getColumnName(i));
            }

            Vector data = new Vector();
            Vector row = new Vector();

            while(rs.next()) {
                row = new Vector(c);

                for(int i = 1; i <= c; i++){
                    row.add(rs.getString(i));
                }

                data.add(row);
            }
            jTable1 = new javax.swing.JTable(data,column);

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Carrinho de Compras");

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

            jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("Modificar item do carrinho");

            jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            jLabel3.setText("ID item:");

            id_item.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

            jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            jLabel4.setText("Quantidade:");

            quant.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

            Cancelar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            Cancelar.setText("Cancelar");
            Cancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    CancelarActionPerformed(evt);
                }
            });

            Remover.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            Remover.setText("Atualizar");
            Remover.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    RemoverActionPerformed(evt);
                }
            });

            pesquisa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan Farina\\Desktop\\IFSP\\3 sem\\LP3\\Trabalho-LP3\\2x\\baseline_search_black_18dp.png")); // NOI18N
            pesquisa.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pesquisaActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Remover))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(id_item, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(quant, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(id_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(8, 8, 8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cancelar)
                        .addComponent(Remover))
                    .addContainerGap())
            );

            AreaCliente.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            AreaCliente.setText("Área de Cliente");
            AreaCliente.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AreaClienteActionPerformed(evt);
                }
            });

            Comprar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            Comprar.setText("Comprar");
            Comprar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ComprarActionPerformed(evt);
                }
            });

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

            jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel5.setText("Adicionar mais itens");

            Comprarmais.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            Comprarmais.setText("Adicionar");
            Comprarmais.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ComprarmaisActionPerformed(evt);
                }
            });

            jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
            jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel6.setText("no carrinho");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(Comprarmais)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel6)
                    .addGap(18, 18, 18)
                    .addComponent(Comprarmais)
                    .addContainerGap(70, Short.MAX_VALUE))
            );

            jTable1.getTableHeader().setFont(new Font("Felix Titling", 0, 18));
            jTable1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            jScrollPane1.setViewportView(jTable1);
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, "ERROR"); }
        finally{
            try{
                st.close();
                rs.close();
                con.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "ERROR CLOSE");
            }
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AreaCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Comprar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AreaCliente)
                    .addComponent(Comprar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AreaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaClienteActionPerformed
        TelaSecundariaCliente telacliente = new TelaSecundariaCliente();
        telacliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_AreaClienteActionPerformed

    private void ComprarmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarmaisActionPerformed
        ComprarTeste comprarmais = new ComprarTeste();
        comprarmais.setVisible(true);
        dispose();
    }//GEN-LAST:event_ComprarmaisActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        id_item.setText("");
        quant.setText("");
    }//GEN-LAST:event_CancelarActionPerformed

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        LocalDate dataLocal = LocalDate.now();
        LocalTime horaLocal = LocalTime.now();
        
        String horarioLocal = horaLocal.toString();
        String DataLocal = dataLocal.toString();
        
        String sql = "select * from carrinho where cpf_cliente = '" + session.getInstance().getCPF() + "' AND aberto = 's'";
        ResultSet rs = bd.consulta(sql);
        //String id1 = null, quant1 = null, preco1 = null;
	try{
            while(rs.next()){
                //id1 = rs.getString("id_produto");
                //quant1 = rs.getString("quant");
                //preco1 = rs.getString("preco_total");
                bd.executa("INSERT INTO compra (id_produto,cpf_cliente,data_compra,hora_compra,valor_total,quantidade) VALUES ('"+rs.getString("id_produto")+"','"+session.getInstance().getCPF()+"','"+DataLocal+"','"+horarioLocal+"','"+rs.getString("preco_total")+"','"+rs.getString("quant")+"')");
            }   
            bd.executa("update carrinho set aberto = 'n' where cpf_cliente = '"+session.getInstance().getCPF()+"' AND aberto = 's'");
        }
        catch(SQLException e){
            System.err.println("Excessão: " + e.toString());
        }
        
        TelaSecundariaCliente telacliente = new TelaSecundariaCliente();
        telacliente.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_ComprarActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        if(Integer.parseInt(quant.getText()) == 0){
            bd.executa("DELETE FROM carrinho where id_produto = '"+id_item.getText()+"'");
        }
        else{
            String sql = "select preco_unit from carrinho where id_produto = '" + id_item.getText() + "'";
            ResultSet rs = bd.consulta(sql);
            float preco_unit = 0, preco_total = 0;
            try{
                while(rs.next()){
                    preco_unit = Float.parseFloat(rs.getString("preco_unit"));
                }   
                preco_total = preco_unit * Integer.parseInt(quant.getText());
            }
            catch(SQLException e){
                System.err.println("Excessão: " + e.toString());
            }
            bd.executa("update carrinho set quant = '"+quant.getText()+"', preco_total = '"+preco_total+"' where id_produto = '"+id_item.getText()+"'");
        }
        atualizarTabela();
        id_item.setText("");
        quant.setText("");
    }//GEN-LAST:event_RemoverActionPerformed

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
        String sql = "select quant from carrinho where cpf_cliente = '" + session.getInstance().getCPF() + "' AND id_produto = '"+id_item.getText()+"'";
        ResultSet rs = bd.consulta(sql);
        String quant1 = null;
	try{
            while(rs.next()){
		quant1 = rs.getString("quant");
            }   
            quant.setText(quant1);
            //quant.enable(true);
        }
        catch(SQLException e){
            System.err.println("Excessão: " + e.toString());
        }
    }//GEN-LAST:event_pesquisaActionPerformed

    private void atualizarTabela(){
        Connection con = null;
        Statement st = null; 
        ResultSet rs = null; String s;

        try{ 
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://ec2-34-195-115-225.compute-1.amazonaws.com:5432/d7gbh9tbts0r7j","zuidrqukwykbwd","8f82c803a029137f140288c3d133e854bdf76d61b948c7ad1365552d7f058d69");
            st = con.createStatement();
            s = "select id_produto,cpf_cliente,quant,preco_total from carrinho where cpf_cliente = '"+session.getInstance().getCPF()+"' AND aberto = 's'"; 
            rs = st.executeQuery(s);
            ResultSetMetaData rsmt = rs.getMetaData(); 
            int c = rsmt.getColumnCount();
            Vector column = new Vector(c);

            for(int i = 1; i <= c; i++) {
                column.add(rsmt.getColumnName(i)); 
            } 

            Vector data = new Vector(); 
            Vector row = new Vector(); 

            while(rs.next()) { 
                row = new Vector(c); 

                for(int i = 1; i <= c; i++){
                    row.add(rs.getString(i)); 
                } 

                data.add(row); 
            }
            jTable1 = new javax.swing.JTable(data,column);
            jTable1.getTableHeader().setFont(new Font("Felix Titling", 0, 18));
            jTable1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            jScrollPane1.setViewportView(jTable1);
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, "ERROR"); }
        finally{
            try{
                st.close(); 
                rs.close(); 
                con.close(); 
            }
            catch(Exception e){ 
                JOptionPane.showMessageDialog(null, "ERROR CLOSE"); 
            } 
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AreaCliente;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Comprar;
    private javax.swing.JButton Comprarmais;
    private javax.swing.JButton Remover;
    private javax.swing.JTextField id_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pesquisa;
    private javax.swing.JTextField quant;
    // End of variables declaration//GEN-END:variables
}
