/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce.compra;

import bancoDados.BD;
import ecommerce.cliente.AreaCliente;
import ecommerce.usuario.session;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ivan Farina
 */
public class PanelCarrinho extends javax.swing.JPanel {

    /**
     * Creates new form PanelCarrinho
     */
    BD bd = new BD();
    AreaCliente ac = new AreaCliente();
    public PanelCarrinho() {
        initComponents();
        bd.conecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        id_item = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        Remover = new javax.swing.JButton();
        quant = new javax.swing.JSpinner();
        ERRO = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        CompraSucesso1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Connection con = null;
        Statement st = null;
        ResultSet rs = null; String s;

        //connect your app to mysql database

        try{
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://ec2-34-195-115-225.compute-1.amazonaws.com:5432/d7gbh9tbts0r7j","zuidrqukwykbwd","8f82c803a029137f140288c3d133e854bdf76d61b948c7ad1365552d7f058d69");
            st = con.createStatement();
            s = "select id_produto AS ID, SUM(quant) AS Quantidade, SUM(preco_total) AS Preco from carrinho where cpf_cliente = '"+session.getInstance().getCPF()+"' AND aberto = 's' group by id_produto";
            rs = st.executeQuery(s);
            ResultSetMetaData rsmt = rs.getMetaData();
            int c = rsmt.getColumnCount();
            Vector column = new Vector(c);

            for(int i = 1; i <= c; i++) {
                column.add(rsmt.getColumnName(i));
            }

            Vector data = new Vector();
            Vector row = new Vector();

            while(rs.next()) {
                row = new Vector(c);

                for(int i = 1; i <= c; i++){
                    row.add(rs.getString(i));
                }

                data.add(row);
            }
            jTable2 = new javax.swing.JTable(data,column);
            jPanel2 = new javax.swing.JPanel();
            Comprar = new javax.swing.JButton();
            jScrollPane3 = new javax.swing.JScrollPane();
            CompraSucesso = new javax.swing.JTextArea();

            setMinimumSize(new java.awt.Dimension(823, 562));
            setPreferredSize(new java.awt.Dimension(823, 562));

            jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Carrinho de Compras");

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESEJA ALTERAR ALGUM ITEM?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 0, 18))); // NOI18N

            jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            jLabel3.setText("ID item:");

            id_item.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            id_item.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    id_itemMouseClicked(evt);
                }
            });

            jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            jLabel4.setText("Quantidade:");

            Cancelar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            Cancelar.setText("Cancelar");
            Cancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    CancelarActionPerformed(evt);
                }
            });

            Remover.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            Remover.setText("Atualizar");
            Remover.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    RemoverActionPerformed(evt);
                }
            });

            quant.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            quant.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
            quant.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    quantMouseClicked(evt);
                }
            });

            ERRO.setFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
            ERRO.setForeground(new java.awt.Color(255, 0, 0));

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precisa de Ajuda?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 18))); // NOI18N

            jButton1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            jButton1.setText("Ajuda");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jScrollPane4.setBorder(null);
            jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

            CompraSucesso1.setEditable(false);
            CompraSucesso1.setBackground(new java.awt.Color(240, 240, 240));
            CompraSucesso1.setColumns(20);
            CompraSucesso1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            CompraSucesso1.setRows(1);
            CompraSucesso1.setText("Caso queira excluir algum item\nou aumentar/diminuir a quantidade\nde algum, clique nesse botão de ajuda\npara tirar suas dúvidas de como fazer.");
            CompraSucesso1.setToolTipText("");
            CompraSucesso1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
            jScrollPane4.setViewportView(CompraSucesso1);

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1)
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(id_item)
                                .addComponent(quant, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Remover))
                        .addComponent(ERRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(id_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ERRO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Cancelar)
                                .addComponent(Remover))))
                    .addContainerGap())
            );

            jTable2.getTableHeader().setFont(new Font("Felix Titling", 0, 18));
            jTable2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            jScrollPane2.setViewportView(jTable2);
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, "ERROR"); }
        finally{
            try{
                st.close();
                rs.close();
                con.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "ERROR CLOSE");
            }
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Finalizar Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 0, 18))); // NOI18N

        Comprar.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Comprar.setText("Finalizar compra");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        CompraSucesso.setEditable(false);
        CompraSucesso.setBackground(new java.awt.Color(240, 240, 240));
        CompraSucesso.setColumns(20);
        CompraSucesso.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        CompraSucesso.setRows(1);
        CompraSucesso.setText("Caso tenha certeza que não quer adicionar mais nenhum item no carrinho, clique no botão \"Finalizar Compra\". ");
        CompraSucesso.setToolTipText("");
        CompraSucesso.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(CompraSucesso);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Comprar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Comprar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        comprar();
    }//GEN-LAST:event_ComprarActionPerformed

    private void id_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_itemMouseClicked
        ERRO.setText("");
    }//GEN-LAST:event_id_itemMouseClicked

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        id_item.setText("");
        quant.setValue(1);
    }//GEN-LAST:event_CancelarActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        atualizarquantidade();
    }//GEN-LAST:event_RemoverActionPerformed

    private void quantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantMouseClicked
        
    }//GEN-LAST:event_quantMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        abrirTelaAjuda();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextArea CompraSucesso;
    private javax.swing.JTextArea CompraSucesso1;
    private javax.swing.JButton Comprar;
    private javax.swing.JLabel ERRO;
    private javax.swing.JButton Remover;
    private javax.swing.JTextField id_item;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JSpinner quant;
    // End of variables declaration//GEN-END:variables

    private void comprar() {
        boolean mensagemerro = false;
        LocalDate dataLocal = LocalDate.now();
        LocalTime horaLocal = LocalTime.now();
        String horarioLocal = horaLocal.toString();
        String DataLocal = dataLocal.toString();

        String sql = "select * from carrinho where cpf_cliente = '" + session.getInstance().getCPF() + "' AND aberto = 's'";
        ResultSet rs = bd.consulta(sql);

        try{
            while(rs.next()){
                bd.executa("INSERT INTO compra (id_produto,cpf_cliente,data_compra,hora_compra,valor_total,quantidade) VALUES ('"+rs.getString("id_produto")+"','"+session.getInstance().getCPF()+"','"+DataLocal+"','"+horarioLocal+"','"+rs.getString("preco_total")+"','"+rs.getString("quant")+"')");
            }
            bd.executa("update carrinho set aberto = 'n' where cpf_cliente = '"+session.getInstance().getCPF()+"' AND aberto = 's'");
            mensagemerro = true;
        }
        catch(SQLException e){
            System.err.println("Excessão: " + e.toString());
        }
        if(mensagemerro=true){
            atualizarTabela();
            CompraSucesso.setText("Compra realizada com sucesso! \n" +"Vá na guia compras e escolha a opção histórico de compras para visualizar os itens comprados!\n" +"Obrigado por comprar com a gente!");
        }
        else{
            CompraSucesso.setText("Seu carrinho não possui itens para realizar a compra.");
        }
    }

    private void atualizarquantidade() {
        boolean r = false;
        String sql = "select preco_unit from carrinho where id_produto = '" + id_item.getText() + "' AND cpf_cliente = '" + session.getInstance().getCPF() + "' AND aberto = 's'";
        ResultSet rs = bd.consulta(sql);
        float preco_unit = 0, preco_total = 0;
        try{
            while(rs.next()){
                preco_unit = Float.parseFloat(rs.getString("preco_unit"));
                r=true;
            }
            preco_total = preco_unit * Integer.parseInt(quant.getValue().toString());
        }
        catch(SQLException e){
            System.err.println("Excessão: " + e.toString());
        }
        finally{
            if(r==false){
                ERRO.setText("PROBLEMA EM ATUALIZAR ITEM");
            }else{
                if(Integer.parseInt(quant.getValue().toString()) == 0){
                    bd.executa("DELETE FROM carrinho where id_produto = '"+id_item.getText()+"'");
                }
                else{
                    bd.executa("update carrinho set quant = '"+quant.getValue().toString()+"', preco_total = '"+preco_total+"' where id_produto = '"+id_item.getText()+"'");
                }
                atualizarTabela();
                id_item.setText("");
                quant.setValue(1);
            }
        }
    }
    
    private void atualizarTabela(){
        Connection con = null;
        Statement st = null; 
        ResultSet rs = null; String s;

        try{ 
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://ec2-34-195-115-225.compute-1.amazonaws.com:5432/d7gbh9tbts0r7j","zuidrqukwykbwd","8f82c803a029137f140288c3d133e854bdf76d61b948c7ad1365552d7f058d69");
            st = con.createStatement();
            s = "select id_produto AS ID, SUM(quant) AS Quantidade, SUM(preco_total) AS Preco from carrinho where cpf_cliente = '"+session.getInstance().getCPF()+"' AND aberto = 's' group by id_produto";
            rs = st.executeQuery(s);
            ResultSetMetaData rsmt = rs.getMetaData(); 
            int c = rsmt.getColumnCount();
            Vector column = new Vector(c);

            for(int i = 1; i <= c; i++) {
                column.add(rsmt.getColumnName(i)); 
            } 

            Vector data = new Vector(); 
            Vector row = new Vector(); 

            while(rs.next()) { 
                row = new Vector(c); 

                for(int i = 1; i <= c; i++){
                    row.add(rs.getString(i)); 
                } 

                data.add(row); 
            }
            jTable2 = new javax.swing.JTable(data,column);
            jTable2.getTableHeader().setFont(new Font("Felix Titling", 0, 18));
            jTable2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
            jScrollPane2.setViewportView(jTable2);
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, "ERROR"); }
        finally{
            try{
                st.close(); 
                rs.close(); 
                con.close(); 
            }
            catch(Exception e){ 
                JOptionPane.showMessageDialog(null, "ERROR CLOSE"); 
            } 
        }
    }

    private void abrirTelaAjuda() {
        TelaAjudaCarrinho telaajuda = new TelaAjudaCarrinho();
        telaajuda.setVisible(true);
    }
}
